### PR TITLE
Compact layout of word usage component

### PR DESCRIPTION
**Pull request by irina060981**
For the issue - https://github.com/alpheios-project/components/issues/350

I have uploaded it to my server for testing: http://alpheios-test-embed.irina-sklyarova.ru/demo/
I have created layout for compact and desktop version.
Here it is screenshots:
**desktop** 
(it is responsive by the width of the panel)
image

**mobile** (browser emulator)
image

**mobile** (phone)
image

----------------------------------
But there are some strange behaviour in compact panel - it scale font inside panel compact according to screen width. I didn't find how it works. And for now - I have increased font inside my tab.
Other tabs are rendered with very small font too.

Also there is a problem with tapping the word.
I have added  this styles to embeded-lib `index.html` to prevent zoom:
```
.alpheios-enabled p {
   touch-action: manipulation;
}
```
Also I have additional problems with tapping - it doesn't select and init search properly.
I need to do it several times to be able to select.

### CODE REVIEW

**Comment by irina060981** [comment]
> I like the little link icon for the citations on mobile.
I think I have missed to show, how source link is working here (after click on the source link - it how fullCit):
image

**Comment by irina060981** [comment]
> I think on the desktop we should have the full citation rather than the link icon though (and once #332 is fixed the panel should resize itself accordingly)

Fixed
image

**Comment by irina060981** [comment]
> Another possibility for the mobile: what if instead of wrapping the text surrounding the target word we truncated it with an elision symbol - truncating from beginning of the prefix and the end of the suffix and then enabled scrolling on the individual sentence within the panel to see the full sentence?

@balmas , I didn't quitely understand what do you mean?
I didn't find in Google what is elision symbol?
And if to be honest - I don't think thst if we try to show each example as a single line + invisible scroll-bar under each line (on mobile it invisible) - it seems to me that it won't be easy to scroll a single line. Or we would need to make it really high and loose all compatible preferences.

Also if we are going to execute selecting the words inside examples (I am not sure, but i remember that we were talking about it before) - it would be really difficult to select and scroll inside one line.
What do you think?

**Comment by balmas** [comment]
@irina060981 those are good points.  An elision symbol is just a ... in place of the text that would normally be shown.

But I think I would like to go ahead and have you commit what you propose and we can get feedback from Monica and Harry and others. I know I am not the best person to make UI decisions :-)

**Pull request merged**
