### PR TITLE
Feat examples fix

### PR DESCRIPTION
**Pull request by balmas**
The purpose of this PR is to nudge the usage examples feature forward a little and experiment with a different display and initial sorting/filtering options. We still have all the open user stories for usage examples. This PR isn't trying to address those, it just responds to some initial feedback on the feature.

1 - we want to try having the default usage examples query to return a max number of hits per author, across all results for all authors. This implements that, although explanation of these settings in the options panel definitely needs work, as does the sorting.

2. we want to try a more traditional concordance display, for at least those devices that have enough room for it. This PR starts on it, but it doesn't finish it mainly because my CSS skills are lacking...  We want the target word to be aligned in the center, with prefix and suffix on the same line.  I have got this mostly working, but the centering isn't quite right still. The target word should be in a line straight down the center.   We still also have to come up with an alternate display for devices where the full example text won't fit on one line. And we might want the display of the citation to include full author names and work titles rather than abbreviations, I'm not sure about this yet.  We also need the panel to resize itself to the ideal size upon opening, but since @kirlat is currently working on this area of the code I didn't try to implement that.
 
3. Another change I made was to directly link the citations, there isn't any need to show the source url itself.

4. Finally I put new icons in for this feature as well as the wordlist feature. There are 2 possible icons for usage examples, we're not sure which one we will go with. It may depend upon what we come up with for the mobile display, because the one I've chosen at the moment is representative of the concordance display and might not work for mobile.

### CODE REVIEW

**Comment by irina060981** [comment]
Hello, @balmas!
I have uploaded your changes to see it myself in embed-lib and see the following problems:

1) usage examples are retrieved, but it is difficult to read  them) :
image

2) option values couldn't be changed - I tried to set value 1 per author, but it cleared and not saved. And now I couldn't set any value - it won't be saved.
I check other options - they are saved properly.

3) what does mean then the value of option `Word Usage Examples - max results for single author request`? I set it to 10 but reciedved 11 results. Or what value should I set to get only 10 results overall?

**Comment by balmas** [comment]
> Hello, @balmas!
> I have uploaded your changes to see it myself in embed-lib and see the following problems:
> 
> 1. usage examples are retrieved, but it is difficult to read  them) :
>    image

This is because the panel is not automatically resized. It needs to be done but since Kirill is working on the panel state/resizing code right now I was going to wait for that.  

> 2. option values couldn't be changed - I tried to set value 1 per author, but it cleared and not saved. And now I couldn't set any value - it won't be saved.

Hmm. That's a bug that I must have missed. 

>    I check other options - they are saved properly.
> 3. what does mean then the value of option `Word Usage Examples - max results for single author request`? I set it to 10 but reciedved 11 results. Or what value should I set to get only 10 results overall?

See my comments in the Client Adapter and Lexical Query code about this.

**Comment by irina060981** [comment]
>See my comments in the Client Adapter and Lexical Query code about this.
Probably I didn't understand correctly the changes in workflow. So as I could see - we now don't have any possibility to limit overall results (without any reference to amount of authors). Of course you know better how it should be right from user perspective.
But from my opinion it is useful for the user to limit overal results:
   - results on the panel could stay compact 
   - it will limit network traffic

**Comment by balmas** [comment]
> > See my comments in the Client Adapter and Lexical Query code about this.
> 
> Probably I didn't understand correctly the changes in workflow. So as I could see - we now don't have any possibility to limit overall results (without any reference to amount of authors). Of course you know better how it should be right from user perspective.
> But from my opinion it is useful for the user to limit overal results:
> 
> * results on the panel could stay compact
> * it will limit network traffic

It's a work in progress .... but the points you are raising are good ones and need a fuller answer. It's probably premature to merge this into master, so let's leave it for now. I will fix the bug with the setting and provide a better explanation of where I think we need to go with the max settings tomorrow. Thank you!

**Comment by balmas** [comment]
@irina060981 I added a further explanation of what I was trying to do here in #307

**Comment by irina060981** [comment]
@balmas, thank you for the explanation! we could really limit the overal amount of examples on the client-side I think - if it would be useful, of course!
I have checked the code - you didn't change it? Options are not saved as before. I dn't need to review the code?

**Pull request merged**
