### PR TITLE
Grammar double scroll + some small fixes

### PR DESCRIPTION
**Pull request by irina060981**
For the issue https://github.com/alpheios-project/components/issues/582

### CODE REVIEW

**Comment by kirlat** [comment]
Unfortunately, this does not work for me. Even with the height of `alpheios-grammar__frame-cont` adjusted to 80vh, the scroll bar still appears 🙁.

image

Also, we could have not only one notification, but two. In that case notification area will take even more space and situation will become worse.

However, I've noticed that if to set  `alpheios-grammar__frame-cont` height small enough, `50vh` let's say, it will still expand itself and occupy the whole vertical space available but not overflow, there will be only one scroll bar, and that's exactly what we need. I, however, did not test it in all browsers, especially on Mac and iOS.

But I still don't have a clue how exactly this works. iFrame content is a very tricky business 🙂. Maybe you will have some ideas?

**Comment by kirlat** [comment]
Here is a screenshot of it with height set to `50vh`. Do not know how, but this works at least in Chrome on Win:
image

**Comment by irina060981** [comment]
@kirlat , thank you for catching this! Will test it again !

**Comment by irina060981** [comment]
I have removed my changes and conpletely remove `height` property from the `alpheios-grammar__frame-cont`, but add `flex-direction`.
This way we have 
   parent: flex, flex: 1 1 auto;
   child: flex, relative
       iframe: absolute
And that's why child gets the whole height.
Here it is description:

https://stackoverflow.com/questions/15381172/how-to-make-flexbox-children-100-height-of-their-parent

I have tested it in Chrome and Firefox

**Comment by irina060981** [comment]
Also I have add really a small fix for the issue - https://github.com/alpheios-project/components/issues/575
added `data-ignore = all` to the source link on mobile - word usage examples tab

**Comment by irina060981** [comment]
And one more tiny fix for showing filters on word usage tab - https://github.com/alpheios-project/components/issues/558

**Comment by irina060981** [comment]
And the last tiy fix - make options (null) disabled in filter select - word usage examples tab

**Comment by kirlat** [comment]
> I have removed my changes and conpletely remove `height` property from the `alpheios-grammar__frame-cont`, but add `flex-direction`.

I think this is an excellent solution, it very flexible as we do not specify direct dimensions anywhere and it adjusts to any content dynamically.

**Pull request merged**
