### PR TITLE
Issue 210

### PR DESCRIPTION
**Pull request by balmas**
Updates providers after retrieving translations. 

See also:
https://github.com/alpheios-project/lemma-client/pull/7
https://github.com/alpheios-project/data-models/pull/55

### CODE REVIEW

**Comment by irina060981** [comment]
And there is some strange problem with popup resizing (try to open **sum** with translations and click **Show credits** and it is in endless loop with resizing.

**Comment by irina060981** [comment]
Also (**sum** is an example) it becomes very wide after showing credits, because of long url, that passes to the next row.
image

I suggest to set max-width for providers.

**Comment by irina060981** [comment]
I have made these fixes myself for my remarks (it seems to me that there is not so much time before release and it could be helpful).

**Comment by balmas** [comment]
thank you for the fixes @irina060981 !

**Pull request merged**
